/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jcgai
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    Operaciones op;
    OperacionesS1 ops;

    public Ventana() {
        this.setTitle("Modelo con tasas de servicio y/o tasas de llegadas dependientes del estado del sistema. ");
        initComponents();
        setLocationRelativeTo(null);//centrar la ventana en la pantalla
        setResizable(false);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelB = new javax.swing.JLabel();
        jLabelA = new javax.swing.JLabel();
        jLabelLanda = new javax.swing.JLabel();
        jLabelMiu = new javax.swing.JLabel();
        jLabelRo = new javax.swing.JLabel();
        jTextFieldS = new javax.swing.JTextField();
        jLabelS = new javax.swing.JLabel();
        jTextFieldA = new javax.swing.JTextField();
        jTextFieldB = new javax.swing.JTextField();
        jTextFieldLanda = new javax.swing.JTextField();
        jTextFieldMiu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelRoR = new javax.swing.JLabel();
        jLabelLandaProm = new javax.swing.JLabel();
        jLabelWq = new javax.swing.JLabel();
        jLabelW = new javax.swing.JLabel();
        jLabelLq = new javax.swing.JLabel();
        jLabelL = new javax.swing.JLabel();
        jLabelP0 = new javax.swing.JLabel();
        jLabelC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelSumatoria = new javax.swing.JLabel();
        jLabelSumCn = new javax.swing.JLabel();
        jLabelSumn1Pn = new javax.swing.JLabel();
        jLabelSumnPn = new javax.swing.JLabel();
        jLabelSumPn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 214, 214), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelB.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabelB.setText("b =");
        jPanel1.add(jLabelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabelA.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabelA.setText("a =");
        jPanel1.add(jLabelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabelLanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/landa.png"))); // NOI18N
        jPanel1.add(jLabelLanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, 30));

        jLabelMiu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miu.png"))); // NOI18N
        jPanel1.add(jLabelMiu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        jLabelRo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ro.png"))); // NOI18N
        jPanel1.add(jLabelRo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 40, 40));
        jPanel1.add(jTextFieldS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 160, 30));

        jLabelS.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabelS.setText("s =");
        jPanel1.add(jLabelS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(jTextFieldA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 160, 30));

        jTextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 160, 30));
        jPanel1.add(jTextFieldLanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 160, 30));
        jPanel1.add(jTextFieldMiu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, 30));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, 30));

        jLabelRoR.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jPanel1.add(jLabelRoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, 30));

        jLabelLandaProm.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabelLandaProm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/landaProm.png"))); // NOI18N
        jPanel1.add(jLabelLandaProm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 230, 30));

        jLabelWq.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabelWq.setText("Wq = ");
        jPanel1.add(jLabelWq, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 230, 30));

        jLabelW.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabelW.setText("W = ");
        jPanel1.add(jLabelW, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 230, 30));

        jLabelLq.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabelLq.setText("Lq = ");
        jPanel1.add(jLabelLq, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 230, 30));

        jLabelL.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabelL.setText("L = ");
        jPanel1.add(jLabelL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 230, 30));

        jLabelP0.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabelP0.setText("P0 = ");
        jPanel1.add(jLabelP0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 230, 30));

        jLabelC.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabelC.setText("c = ");
        jPanel1.add(jLabelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 610));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 214, 214), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "n", "cn", "Pn", "nPn", "(n-1)Pn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 720, 540));

        jLabelSumatoria.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabelSumatoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sum.png"))); // NOI18N
        jLabelSumatoria.setText("=");
        jPanel2.add(jLabelSumatoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 50, 30));

        jLabelSumCn.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jPanel2.add(jLabelSumCn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 140, 30));

        jLabelSumn1Pn.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jPanel2.add(jLabelSumn1Pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 140, 30));

        jLabelSumnPn.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jPanel2.add(jLabelSumnPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 140, 30));

        jLabelSumPn.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jPanel2.add(jLabelSumPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 140, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 740, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabelC.setText("c = ");
        jLabelP0.setText("P0 = ");
        jLabelL.setText("L = ");
        jLabelLq.setText("Lq = ");
        jLabelW.setText("W = ");
        jLabelWq.setText("Wq = ");

        validar();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void MostrarDatos() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                op.GenArreglos(),
                new String[]{
                    "n", "cn", "Pn", "nPn", "(n-1)Pn"
                }
        ));
    }

    public void MostrarDatos1() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                ops.GenArreglos(),
                new String[]{
                    "n", "cn", "Pn", "nPn", "(n-1)Pn"
                }
        ));
    }

    private void validar() {
        if (jTextFieldA.getText().length() != 0 && jTextFieldB.getText().length() != 0
                && jTextFieldLanda.getText().length() != 0 && jTextFieldMiu.getText().length() != 0 && jTextFieldS.getText().length() != 0) {

            double a, b, landa, miu;
            int s;

            a = Double.parseDouble(jTextFieldA.getText());
            b = Double.parseDouble(jTextFieldB.getText());
            landa = Double.parseDouble(jTextFieldLanda.getText());
            miu = Double.parseDouble(jTextFieldMiu.getText());
            s = Integer.parseInt(jTextFieldS.getText());

            if (Integer.parseInt(jTextFieldS.getText()) > 1) {

                op = new Operaciones(a, b, landa, miu, s);
                op.Operaciones();

                jLabelRoR.setText(String.valueOf(op.ro));
                jLabelC.setText(jLabelC.getText() + String.valueOf(op.c));
                jLabelP0.setText(jLabelP0.getText() + String.valueOf(String.format("%.8f", op.p0)));
                jLabelL.setText(jLabelL.getText() + String.valueOf(String.format("%.8f", op.acunpn)));
                jLabelLq.setText(jLabelLq.getText() + String.valueOf(String.format("%.8f", op.acun1pn)));
                jLabelLandaProm.setText(String.valueOf(String.format("%.8f", op.acunlandan)));
                jLabelW.setText(jLabelW.getText() + String.valueOf(String.format("%.8f", op.w)));
                jLabelWq.setText(jLabelWq.getText() + String.valueOf(String.format("%.8f", op.wq)));

                jLabelSumCn.setText(String.valueOf(String.format("%.8f", op.acucn)));
                jLabelSumCn.setHorizontalAlignment(SwingConstants.CENTER);
                jLabelSumPn.setText(String.valueOf(String.format("%.0f", op.acupn)));
                jLabelSumPn.setHorizontalAlignment(SwingConstants.CENTER);
                jLabelSumnPn.setText(String.valueOf(String.format("%.8f", op.acunpn)));
                jLabelSumCn.setHorizontalAlignment(SwingConstants.CENTER);
                jLabelSumn1Pn.setText(String.valueOf(String.format("%.8f", op.acun1pn)));
                jLabelSumCn.setHorizontalAlignment(SwingConstants.CENTER);

                op.GenArreglos();

                MostrarDatos();
            } else {
                ops = new OperacionesS1(a, b, landa, miu, s);
                ops.Operaciones();

                jLabelRoR.setText(String.valueOf(ops.ro));
                jLabelC.setText(jLabelC.getText() + String.valueOf(ops.c));
                jLabelP0.setText(jLabelP0.getText() + String.valueOf(String.format("%.8f", ops.p0)));
                jLabelL.setText(jLabelL.getText() + String.valueOf(String.format("%.8f", ops.acunpn)));
                jLabelLq.setText(jLabelLq.getText() + String.valueOf(String.format("%.8f", ops.acun1pn)));
                jLabelLandaProm.setText(String.valueOf(String.format("%.8f", ops.acunlandan)));
                jLabelW.setText(jLabelW.getText() + String.valueOf(String.format("%.8f", ops.w)));
                jLabelWq.setText(jLabelWq.getText() + String.valueOf(String.format("%.8f", ops.wq)));

                jLabelSumCn.setText(String.valueOf(String.format("%.8f", ops.acucn)));
                jLabelSumCn.setHorizontalAlignment(SwingConstants.CENTER);
                jLabelSumPn.setText(String.valueOf(String.format("%.0f", ops.acupn)));
                jLabelSumPn.setHorizontalAlignment(SwingConstants.CENTER);
                jLabelSumnPn.setText(String.valueOf(String.format("%.8f", ops.acunpn)));
                jLabelSumCn.setHorizontalAlignment(SwingConstants.CENTER);
                jLabelSumn1Pn.setText(String.valueOf(String.format("%.8f", ops.acun1pn)));
                jLabelSumCn.setHorizontalAlignment(SwingConstants.CENTER);

                ops.GenArreglos();

                MostrarDatos1();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese todos los datos. ");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelL;
    private javax.swing.JLabel jLabelLanda;
    private javax.swing.JLabel jLabelLandaProm;
    private javax.swing.JLabel jLabelLq;
    private javax.swing.JLabel jLabelMiu;
    private javax.swing.JLabel jLabelP0;
    private javax.swing.JLabel jLabelRo;
    private javax.swing.JLabel jLabelRoR;
    private javax.swing.JLabel jLabelS;
    private javax.swing.JLabel jLabelSumCn;
    private javax.swing.JLabel jLabelSumPn;
    private javax.swing.JLabel jLabelSumatoria;
    private javax.swing.JLabel jLabelSumn1Pn;
    private javax.swing.JLabel jLabelSumnPn;
    private javax.swing.JLabel jLabelW;
    private javax.swing.JLabel jLabelWq;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldA;
    private javax.swing.JTextField jTextFieldB;
    private javax.swing.JTextField jTextFieldLanda;
    private javax.swing.JTextField jTextFieldMiu;
    private javax.swing.JTextField jTextFieldS;
    // End of variables declaration//GEN-END:variables
}
